variable "aro_cluster_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "domain" {}
variable "openshift_version" {}
variable "pull_secret" {}
variable "client_id" {}
variable "client_secret" {}
variable "pod_cidr" {}
variable "service_cidr" {}
variable "master_vm_size" {}
variable "master_subnet_id" {}
variable "worker_vm_size" {}
variable "worker_subnet_id" {}
variable "worker_count" {}
variable "worker_disk_size_gb" {}
variable "apiserver_visibility" {}
variable "ingress_visibility" {}
